# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97c267bc26ec922525502983b2d2c4a09a3ac70b28852a11a8db939ebff81cb35dcf61c103a5bfc10c63d49d6c06968d00fa54036dd53d06b4ef0bc54da397f2

test:
  secret_key_base: f9b492e985d5131ef1e9b433baeb7ae8ada7f9e82c466d4c647019684dc8ec0586f126d73a87b8c2106c3f8d3e7d455f462b72afb8df4a18e28070b763647598

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
